# Generated by Django 2.2.7 on 2020-09-25 05:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200925_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
